int upperBits(int);
int test_upperBits(int);
int implication(int, int);
int test_implication(int, int);
int byteSwap(int, int, int);
int test_byteSwap(int, int, int);
int sign(int);
int test_sign(int);
int sm2tc(int);
int test_sm2tc(int);
int bitParity(int);
int test_bitParity(int);
int tmax();
int test_tmax();
int rempwr2(int, int);
int test_rempwr2(int, int);
int isGreater(int, int);
int test_isGreater(int, int);
int satMul3(int);
int test_satMul3(int);
int trueFiveEighths(int);
int test_trueFiveEighths(int);
int howManyBits(int);
int test_howManyBits(int);
