#
# This file contains course and lab specific parameters for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "autolab.cs.cmu.edu";
$SERVER_PORT = "80";
$COURSE_NAME = "15213-s06";
$AUTOGRADE_TIMEOUT = "300";
1;
